### ISSUE TITLE
Complete the ci pipeline

### ISSUE THREAD

**Issue by JooKS-me** [apache/shenyu-helm-chart#7]
There are some error in `ci`, because of the use of third-party actions. 

For the use of third-party jobs, we can try to implement it in another way, or put open source jobs in the form of submodules into our project.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/62384022/177025513-dc0c66c9-7ea4-4324-a9c7-35aa11e4c44c.png">

Ref https://github.com/apache/incubator-shenyu-helm-chart/actions/runs/2603898249

/cc @erdengk

**Comment by erdengk** [comment]
ok，I get it.
Please pay attention it. @aFlyBird0

**Comment by aFlyBird0** [comment]
> 

Copy that, thank you both. @erdengk @JooKS-me ❤️ 

I have previously found a way to circumvent the apace check by `git sumodule` in other apache projects. This coincides with JooKS-me's tip, thanks!

I'll be taking over from @erdengk , thanks!
